name: Generate PR description

on:
  pull_request:
    types: [opened]

jobs:
  pr-desc-creation:
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      pull-requests: write 

    steps:
      - name: Checkout Actual Repo
        uses: actions/checkout@v3
      
      - name: Checkout Repo POC
        uses: actions/checkout@v3
        with:
          repository: ibm-q-research/poc-swe-agent-quantum
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: poc-swe-agent-quantum
          server-url: https://github.ibm.com 
      
      - name: Run POC script for desc
        id: run_analysis
        run: |
          cd poc-swe-agent-quantum
          files=$(ls -1)
          echo "Files in repoB:"
          echo "$files"
          echo "pr_description<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR with Desc
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Automated Analysis:**
            ${{ steps.run_analysis.outputs.pr_description }}
